### ISSUE TITLE
openssl-1.0.2p.tar.gz链接失效以及SSRPLUS添加服务器界面报错

### ISSUE THREAD

**Issue by shikkoku** [ntlf9t/openwrt18.06#1]
![855220435_225038](https://user-images.githubusercontent.com/4697177/65382528-262f8180-dd3a-11e9-8b23-ff8cdae2932e.jpg)

![Annotation 2019-09-22 042326](https://user-images.githubusercontent.com/4697177/65382530-27f94500-dd3a-11e9-879c-b661ad69f062.jpg)

问题一可以用现成已有的文件覆盖到dl文件夹里。

问题二不知道怎么破。

**Comment by ntlf9t** [comment]
安装 luci-app-filetransfer
